name: Automerge

on:

  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:

  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash